const TotalSongsList = [
  {
    title: 'RUKUM MAIKOT-New Nepali Movie khusma Song 2024',
    thumbnailaddress: 'ThumbnailPic\\1.jpg',
    mp3add: 'mp3\\1.mp3',
    featuring: 'Dhiraj Magar,Upasana Singh Thakuri',
    singer: 'SD Yogi, Shanti shree pariyar',
    relaseDate: '24 Aug 2024',
    youtubeViews: '50,638,719',
    youtubechannel: 'https://www.youtube.com/@KendraMotionPictures',
    youtubeLogo: 'images\\youtubeLogo.png',
    video: 'https://www.youtube.com/embed/p7wDS1VV3n4?si=Rak555To633H5mwR',
    playListTitle: 'Nepalisongs',
  },
  {
    title: 'Ghumi Ghumi - A Folk Journey',
    thumbnailaddress: 'ThumbnailPic\\2.jpg',
    mp3add: 'mp3\\2.mp3',
    featuring: 'Bipin Karki & Anjana Baraili',
    singer: 'Sujan Chapagain, Shanti Shree Pariyar',
    relaseDate: '09 Apr 2022',
    youtubeViews: '17,577,591',
    youtubechannel: 'https://www.youtube.com/@SujanChapagain',
    youtubeLogo: 'images\\youtubeLogo.png',
    video: 'https://www.youtube.com/embed/_60Q8Xg4Mp0?si=-18MwMmDDh00W1ls',
    playListTitle: 'Lovesongs',
  },
  {
    title: 'फूल [Phool] Film ऊनको स्वीटर',
    thumbnailaddress: 'ThumbnailPic\\3.jpg',
    mp3add: 'mp3\\3.mp3',
    featuring: 'Bipin karki & Miruna Magar',
    singer: 'Sujan Chapagain, Bidhya Tiwari, Jhuma Limbu',
    relaseDate: '14 Feb 2024',
    youtubeViews: '14,390,077 ',
    youtubechannel: 'https://www.youtube.com/@artmandu',
    youtubeLogo: 'images\\youtubeLogo.png',
    video: 'https://www.youtube.com/embed/DXStTwh9SSA?si=lmOh4B2O4UrCfd9V',
    playListTitle: 'Nepalisongs',
  },
  {
    title: 'Sajjan Raj Vaidya - Dhairya [Official Release]',
    thumbnailaddress: 'ThumbnailPic\\4.jpg',
    mp3add: 'mp3\\4Dhairya.mp3',
    featuring: 'Sajjan Raj Vaidya',
    singer: 'Sajjan Raj Vaidya',
    relaseDate: '21 Oct 2022',
    youtubeViews: '44,576,952',
    youtubechannel: 'https://www.youtube.com/@sajjanrajvaidya',
    youtubeLogo: 'images\\youtubeLogo.png',
    video: 'https://www.youtube.com/embed/6FEsFvZ-hqY?si=IjOFd3RcQpBTViA_',
    playListTitle: 'OneSidedLove',
  },
  {
    title: 'Nepathya - Rato ra Chandra Surya (रातो र चन्द्रसूर्य)',
    thumbnailaddress: 'ThumbnailPic\\5.jpg',
    mp3add: 'mp3\\5.mp3',
    featuring: 'Nepathya',
    singer: 'Nepathya',
    relaseDate: '23 Jul 2019',
    youtubeViews: '5,485,184',
    youtubechannel: 'https://www.youtube.com/@NepathyaOfficial',
    youtubeLogo: 'images\\youtubeLogo.png',
    video: 'https://www.youtube.com/embed/biufV1olDes?si=Mol-DhSf55uyjWN9',
    playListTitle: 'Nepalisongs',
  },
  {
    title: 'Sajjan Raj Vaidya - Naganya Maya [Official Release]',
    thumbnailaddress: 'ThumbnailPic\\6.jpg',
    mp3add: 'mp3\\6.mp3',
    featuring: 'Sajjan Raj Vaidya',
    singer: 'Sajjan Raj Vaidya',
    relaseDate: '31 Oct 2021',
    youtubeViews: '45,913,120',
    youtubechannel: 'https://www.youtube.com/@sajjanrajvaidya',
    youtubeLogo: 'images\\youtubeLogo.png',
    video: 'https://www.youtube.com/embed/csoXwcbmNLw?si=wggW0TZXFY0IzprY',
    playListTitle: 'Breakup',
  },
  {
    title: 'Aama आमा - Laxmi (Lyrics Video)',
    thumbnailaddress: 'ThumbnailPic\\7.jpg',
    mp3add: 'mp3\\7.mp3',
    featuring: 'Laxmi Thapa',
    singer: 'Laxmi Thapa',
    relaseDate: '14 Dec 2022',
    youtubeViews: '1,935,185',
    youtubechannel: 'https://www.youtube.com/@laxmithapa3185',
    youtubeLogo: 'images\\youtubeLogo.png',
    video: 'https://www.youtube.com/embed/LHPjYtm_LtI?si=i3kHJHtkov03pZ9R',
    playListTitle: 'Nepalisongs',
  },
  // {
  //   title:
  // }
]

// module.expoorts = TotalSongsList
